//
//  Workspace.swift
//
//  Created by 이정원 on 4/3/26.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: ProjectInfo.appName,
    projects: ["Projects/**"],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
